### ISSUE TITLE
publishShp does not support Chinese file name

### ISSUE THREAD

**Issue by coderdream** [geosolutions-it/geoserver-manager#242]
I copy a zip file to testdata folder and get error message:
`
java.lang.IllegalArgumentException: Invalid uri 'http://172.16.104.131:31911/geoserver/rest/workspaces/file-manage/datastores/污水管点/file.shp?configure=none': escaped absolute path not valid

	at org.apache.commons.httpclient.HttpMethodBase.<init>(HttpMethodBase.java:222)
	at org.apache.commons.httpclient.methods.ExpectContinueMethod.<init>(ExpectContinueMethod.java:93)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.<init>(EntityEnclosingMethod.java:119)
	at org.apache.commons.httpclient.methods.PutMethod.<init>(PutMethod.java:76)
	at it.geosolutions.geoserver.rest.HTTPUtils.put(HTTPUtils.java:234)
	at it.geosolutions.geoserver.rest.HTTPUtils.put(HTTPUtils.java:160)
	at it.geosolutions.geoserver.rest.GeoServerRESTPublisher.createStore(GeoServerRESTPublisher.java:860)
	at it.geosolutions.geoserver.rest.GeoServerRESTPublisher.createDataStore(GeoServerRESTPublisher.java:903)
	at it.geosolutions.geoserver.rest.GeoServerRESTPublisher.publishShp(GeoServerRESTPublisher.java:1134)
	at it.geosolutions.geoserver.rest.GeoServerRESTPublisher.publishShp(GeoServerRESTPublisher.java:1248)
	at it.geosolutions.geoserver.rest.GeoServerRESTPublisher.publishShp(GeoServerRESTPublisher.java:1054)
	at it.geosolutions.geoserver.rest.publisher.GeoserverRESTShapeTest.testReloadDataStore_02(GeoserverRESTShapeTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.rules.TestWatchman$1.evaluate(TestWatchman.java:48)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

`

![image](https://user-images.githubusercontent.com/1549511/177068681-0b1499f1-eee6-445d-b3c9-c72980e99e94.png)

**Comment by Arjen10** [comment]
这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了

**Comment by BadwomenzzzZ** [comment]
> 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了

可以具体说一下怎么改吗 我这边也遇到了这样的问题

**Comment by Arjen10** [comment]
> > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> 
> 可以具体说一下怎么改吗 我这边也遇到了这样的问题

你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难

**Comment by BadwomenzzzZ** [comment]
> > > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> > 
> > 
> > 可以具体说一下怎么改吗 我这边也遇到了这样的问题
> 
> 你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难

爱你 天皇❤❤❤

**Comment by BadwomenzzzZ** [comment]
> > > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> > 
> > 
> > 可以具体说一下怎么改吗 我这边也遇到了这样的问题
> 
> 你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难

我拉了你的分支了 本地发了个快照仓库试了一下 还是不行 
![image](https://user-images.githubusercontent.com/70122672/209045998-c4c964e8-4a69-4a77-9086-512b6fecde1b.png)

**Comment by Arjen10** [comment]
> > > > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> > > 
> > > 
> > > 可以具体说一下怎么改吗 我这边也遇到了这样的问题
> > 
> > 
> > 你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难
> 
> 我拉了你的分支了 本地发了个快照仓库试了一下 还是不行 ![image](https://user-images.githubusercontent.com/70122672/209045998-c4c964e8-4a69-4a77-9086-512b6fecde1b.png)

![image](https://user-images.githubusercontent.com/47875127/209046607-bf6ae511-2a12-4783-b2ac-127becf1c5c3.png)
这是我对我仓库里面的geoserver-manager二次封装的一个工具包，完全没问题

**Comment by BadwomenzzzZ** [comment]
> > > > > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> > > > 
> > > > 
> > > > 可以具体说一下怎么改吗 我这边也遇到了这样的问题
> > > 
> > > 
> > > 你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难
> > 
> > 
> > 我拉了你的分支了 本地发了个快照仓库试了一下 还是不行 ![image](https://user-images.githubusercontent.com/70122672/209045998-c4c964e8-4a69-4a77-9086-512b6fecde1b.png)
> 
> ![image](https://user-images.githubusercontent.com/47875127/209046607-bf6ae511-2a12-4783-b2ac-127becf1c5c3.png) 这是我对我仓库里面的geoserver-manager二次封装的一个工具包，完全没问题

我这个报错不是中文问题的报错了 是文件同http上传的报错 没法在服务器端解压:<

**Comment by Arjen10** [comment]
> > > > > > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> > > > > 
> > > > > 
> > > > > 可以具体说一下怎么改吗 我这边也遇到了这样的问题
> > > > 
> > > > 
> > > > 你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难
> > > 
> > > 
> > > 我拉了你的分支了 本地发了个快照仓库试了一下 还是不行 ![image](https://user-images.githubusercontent.com/70122672/209045998-c4c964e8-4a69-4a77-9086-512b6fecde1b.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/47875127/209046607-bf6ae511-2a12-4783-b2ac-127becf1c5c3.png) 这是我对我仓库里面的geoserver-manager二次封装的一个工具包，完全没问题
> 
> 我这个报错不是中文问题的报错了 是文件同http上传的报错 没法在服务器端解压:<

debug一下吧，我司大家用起来都很正常

**Comment by BadwomenzzzZ** [comment]
> > > > > > > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> > > > > > 
> > > > > > 
> > > > > > 可以具体说一下怎么改吗 我这边也遇到了这样的问题
> > > > > 
> > > > > 
> > > > > 你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难
> > > > 
> > > > 
> > > > 我拉了你的分支了 本地发了个快照仓库试了一下 还是不行 ![image](https://user-images.githubusercontent.com/70122672/209045998-c4c964e8-4a69-4a77-9086-512b6fecde1b.png)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/47875127/209046607-bf6ae511-2a12-4783-b2ac-127becf1c5c3.png) 这是我对我仓库里面的geoserver-manager二次封装的一个工具包，完全没问题
> > 
> > 
> > 我这个报错不是中文问题的报错了 是文件同http上传的报错 没法在服务器端解压:<
> 
> debug一下吧，我司大家用起来都很正常

okk 阿里嘎多

**Comment by Johnnychentong** [comment]
请问解决了吗  中文shp文件还是传不上去报一样的错

**Comment by Johnnychentong** [comment]
> > > > > > > > 这个仓库早就停止更新了，你需要把源码里面的url编码一下就行了
> > > > > > > 
> > > > > > > 
> > > > > > > 可以具体说一下怎么改吗 我这边也遇到了这样的问题
> > > > > > 
> > > > > > 
> > > > > > 你可以去看看我fork的仓库，这里面我是改好了的，里面也有我提交的记录，完全支持中文shapefile上传，你只需要拉下来自己打个包，maven引入就行。但是还是建议你拉源码自己debug下去看看，这个改起来不难
> > > > > 
> > > > > 
> > > > > 我拉了你的分支了 本地发了个快照仓库试了一下 还是不行 ![image](https://user-images.githubusercontent.com/70122672/209045998-c4c964e8-4a69-4a77-9086-512b6fecde1b.png)
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/47875127/209046607-bf6ae511-2a12-4783-b2ac-127becf1c5c3.png) 这是我对我仓库里面的geoserver-manager二次封装的一个工具包，完全没问题
> > > 
> > > 
> > > 我这个报错不是中文问题的报错了 是文件同http上传的报错 没法在服务器端解压:<
> > 
> > 
> > debug一下吧，我司大家用起来都很正常
> 
> okk 阿里嘎多

请问解决了吗 中文shp文件还是传不上去报一样的错

**Comment by Arjen10** [comment]
> 请问解决了吗 中文shp文件还是传不上去报一样的错

确保你的shp压缩包的名称跟shp文件名称一致，且shp压缩包里面不要出现文件夹目录，压缩包打开就是shp文件
